name: Industrialisation continue sur le serveur AWS (Tomcat)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create WAR file
      run: jar cvf CisseModou.war *

    - name: Copy file via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        source: "CisseModou.war"
        target: "/opt/tomcat/webapps"
